import Head from 'next/head';
import React, { useRef } from 'react';
import { useState } from "react";
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillLinkedin, AiFillYoutube } from 'react-icons/ai';
import { FaGithub } from "react-icons/fa";
import Image from "next/image";
import DashboardImage from '../public/DashboardImage.jpg';
import Logo from "../public/Logo.png";
import eLogo from "../public/eLogo.png";
import myImg from "../public/myImg.jpg";
import Recipeapi from "../public/Recipeapi.png";
import flighthub from "../public/flighthub.png"
import CCSAI from "../public/CCSAI.png"

export default function Home() {
  const [isOpen, setIsOpen] = useState(false);

  const handleButtonClick = () => {
    // Open the project link in a new tab
    window.open('https://recipeapi-f6mb.vercel.app/', '_blank');
  };


  const handleButtonEmail = () => {
    // Open the default email client with a pre-filled email
    window.location.href = 'mailto:mk0805511@gmail.com';
  };

  const [darkMode, setDarkMode] = useState(false);
  return (

    <div className={darkMode ? "dark" : ""}>

      <>
        <Head>
          <title>Mandeep Kaur Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
          <section className="min-h-screen">
            <nav className="py-10 mb-12 flex justify-between">
              <h1 className="text-xl font-burtons  dark:text-white"> Developed by Mandeep Kaur</h1>
              <ul className="flex items-center">
                <li>
                  <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl  dark:text-white" />
                </li>
                <li>
                  <a className="bg-gradient-to-r from bg-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="/#">Resume</a></li>
              </ul>
            </nav>
            <div className="text-center p-10">
              <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">Mandeep Kaur</h2>
              <h3 className="text-2xl py-2 md:text-3xl  dark:text-white">A computer science student from Canada. I excel in development using MERN stack. I also aim to deepen my understanding in various areas of technology and product development .</h3>
              <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto  dark:text-white">  </p>
            </div>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600  dark:text-white">
              <a href="https://www.linkedin.com/in/mandeep-kaur-a12201256/"><AiFillLinkedin /></a>
              <a href="https://www.youtube.com/channel/UC6zYvZHoW9NrZJJpIovXc1Q"><AiFillYoutube /></a>
              <a href="https://github.com/Mandeep180"><FaGithub /></a>

            </div>
            <div className="relative mx-auto  rounded-full w-80 h-50 mt-20 ">
              <Image src={myImg} />
            </div>
          </section>



          <section>

            <div className="lg:center gap-10">

              <div className="text-center  shadow-lg p-10 rounded-xl my-10  dark:bg-black relative mx-auto  bg-slate-50">
                <h3 className=" text-3xl py-1 mt-20 text-center font-burtons  dark:text-white ">Education</h3>
                <Image src={Logo} width={400} height={200} className="mx-auto my-10" />
                {/* <h2 className="text-lg font-medium pt-8 pb-2">Centennial College- Toronto CAN</h2> */}
                <h3 className="text-2xl py-2 md:text-3xl  dark:text-white">Centennial College- Toronto CA</h3>
                <h2 className="text-xl py-2 md:text-2xl  dark:text-white"> I Studied Software Engineering</h2>
              </div>
            </div>
          </section>



          <section>
            <div className="lg:center ">

              <div className="text-center  shadow-lg p-10 rounded-xl my-10  dark:bg-black relative mx-auto  bg-slate-50">
                <h3 className=" text-3xl py-1 mt-20 text-center font-burtons  dark:text-white">Experience</h3>
                <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-black relative mx-auto bg-slate-50">
                  <Image src={eLogo} width={400} height={200} className="mx-auto my-10" />
                  <h2 className="text-2xl py-2 md:text-2xl dark:text-white">FrontEnd Developer @ WIMTACH, Centennial College- Toronto CA</h2>
                  <p className="dark:text-white">November 2022 - March 2023 (Internship)</p>
                  <p className="text-gray-800 text-xl py-2 md:text-xl dark:text-white">
                    Developed a responsive React website from scratch, both on the client and server side, for an association. The website is used on a massive scale by disabled students and health workers. Collaborated with project stakeholders and product management following best practices for the full software development life cycle, including coding standards, code reviews, source control management, build processes, testing, and operations.
                  </p>
                  <div className="flex justify-center mt-4">
                    <button className="bg-white border-black text-black px-4 py-2 mr-2 rounded-md">React</button>
                    <button className="bg-white border-black text-black px-4 py-2 mr-2 rounded-md">MongoDB</button>
                    <button className="bg-white border-black text-black px-4 py-2 mr-2 rounded-md">Express</button>
                    <button className="bg-white border-black text-black px-4 py-2 mr-2 rounded-md">Nodejs</button>
                    <button className="bg-white border-black text-black px-4 py-2 rounded-md">Figma</button>


                  </div>
                </div>
                <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-black relative mx-auto bg-slate-50">
                  <Image src={flighthub} width={400} height={200} className="mx-auto my-10" />
                  <h2 className="text-2xl py-2 md:text-2xl dark:text-white">Software QA analyst @ FlightHub, Montreal CA</h2>
                  <p className="dark:text-white">August 2023 - still here</p>
                  <p className="text-gray-800 text-xl py-2 md:text-xl dark:text-white">
                    As a part of the Content Integration team, I skillfully utilized POSTMAN for precise API testing and demonstrated proficiency in leveraging SQL for efficient data handling. My collaboration with Developers and Stakeholders led to a 15% increase in accuracy during test planning and execution. Meticulous documentation resulted in alot of reduction in post-release defects, while proactive test strategy creation contributed to a 30% improvement in testing effectiveness. Collaborative problem-solving led to a 40% increase in product stability, ensuring the delivery of a top-notch product to end-users.
                  </p>
                </div>
                <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-black relative mx-auto bg-slate-50">
                  <Image src={CCSAI} width={400} height={200} className="mx-auto my-10" />
                  <h2 className="text-2xl py-2 md:text-2xl dark:text-white">Mentor @ CCSAI, Centennial College - Toronto CA</h2>
                  <p className="dark:text-white">September 2022 - December 2022</p>
                  <p className="text-gray-800 text-xl py-2 md:text-xl dark:text-white">
                    As a Mentor at Centennial College Student Association, I played an important role in supporting the integration of international students into the college community. My commitment extended to addressing weekly inquiries from international students, offering insights, and aiding them with study-related queries, particularly in the field of Software Engineering. Through these efforts, I contributed to fostering a supportive and inclusive atmosphere for students from diverse backgrounds.
                  </p>
                </div>

              </div>
            </div>
          </section>


          <section>

            <div className="lg:center ">

              <div className="text-center  shadow-lg p-10 rounded-xl my-10  dark:bg-black relative mx-auto  bg-slate-50">
                <div >
                  <h3 className="text-3xl py-1 mt-20 text-center font-burtons  dark:text-white">Side Projects</h3>
                  <p className="text-md py-2 leading-8 text-gray-800 md:text-xl  dark:text-white">
                    Since im just in the beginning of my career as a software developer, I've done <span className="text-md py-2 text-teal-600">freelancing</span> for students websites and <span className="text-md py-2 text-teal-600">collaborated</span> with WIMTACH a association at my college to build a <span className="text-md py-2 text-teal-600">beautiful website</span> to support special aid students.
                  </p>
                  <p className="text-md py-2 leading-8 text-gray-800 md:text-xl  dark:text-white">
                    I offer various services which include designing, front end development using MERN stack, Javascript, Html, css, Nextjs, C#, java.
                  </p>
                </div>
                <div className="lg:flex gap-10">
                  <div className="text-center  shadow-lg p-10 rounded-xl my-10 dark:bg-white">
                    <Image src={Recipeapi} width={300} height={200} className="my-10 mx-auto" />
                    <h3 className="text-lg font-medium pt-8 pb-2">Recipe Search API</h3>

                    <p className="text-gray-800 py-1">Find the recipes of tens of thousands of dishes</p>
                    <button onClick={handleButtonClick} className=" bg-cyan-500 to-teal-500 text-black px-4 py-2 mr-2 rounded-md"> Open Project

                    </button><br></br>
                    <a href="https://github.com/Mandeep180/Recipeapi.git" className="py-4 text-teal-600">Git Repo, Click Here!</a>

                  </div>
                  <div className="text-center  shadow-lg p-10 rounded-xl my-10  dark:bg-white">
                    <Image src={Recipeapi} width={300} height={200} className="my-10 mx-auto" />
                    <h3 className="text-lg font-medium pt-8 pb-2">Doctor Appointment</h3>
                    <p>In progress!!!</p>
                    <p className="text-gray-800 py-1">Find the recipes of tens of thousands of dishes</p>
                    <button onClick={handleButtonClick} className=" bg-cyan-500 to-teal-500 text-black px-4 py-2 mr-2 rounded-md"> Open Project

                    </button><br></br>
                    <a href="https://github.com/Mandeep180/Recipeapi.git" className="py-4 text-teal-600">Git Repo, Click Here!</a>

                  </div>
                  <div className="text-center  shadow-lg p-10 rounded-xl my-10 dark:bg-white">
                    <Image src={DashboardImage} width={180} height={120} className="mt-10" />
                    <h3 className="text-lg font-medium pt-8 pb-2">Software Development project</h3>
                    <p className="py-2">
                      <a className="bg-gradient-to-r from bg-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="https://docs.google.com/document/d/1nAdSA7YXLn4WuAo4H3JiNf7xmAUKQv4wd0tbchhQ2Eg/edit?usp=sharing">Document</a>
                    </p>
                    <h4 className="py-4 text-teal-600">Software testing</h4>
                    <p className="text-gray-800 py-1">Full stack app MERN Stack</p>
                    <p className="text-gray-800 py-1">Test cases, Test Plans</p>
                    <p className="text-gray-800 py-1">Types Of Testing</p>

                  </div>
                </div>
              </div>
            </div>

          </section>



          <section>

            <div className="lg:center ">

              <div className="text-center  shadow-lg p-10 rounded-xl my-10  dark:bg-black relative mx-auto  bg-slate-50">
                <div >
                  <h3 className="text-3xl py-1 mt-20 text-center font-burtons  dark:text-white">Skills</h3>
                </div>


                <div className="lg:flex gap-10">
                  <div className="text-center  shadow-lg p-10 rounded-xl my-10 dark:bg-white">
                    <h3 className="text-2xl font-medium pt-8 pb-2 text-teal-600">BackEnd</h3>

                    <p className="py-2 text-teal-600">
                      Backend skills practiced on various projects.
                    </p>
                    <h2 className="text-left "> Express.JS-Experienced</h2><br></br>
                    <div
                      className="bg-[#30E3CA] h-2.5 rounded-full ">
                    </div><br></br>

                    <h2 className="text-left "> Node.JS-Experienced</h2> <br></br>
                    <div
                      className="bg-[#30E3CA] h-2.5 rounded-full ">
                    </div><br></br>
                    <h2 className="text-left ">MongoDB-Experienced</h2><br></br>
                    <div
                      className="bg-[#30E3CA] h-2.5 rounded-full ">
                    </div><br></br>
                    <h2 className="text-left ">C#-Basic</h2> <br></br>
                    <div
                      className="bg-[#30E3CA] h-2.5 rounded-full ">
                    </div><br></br>
                    <h2 className="text-left ">SQL-Basic</h2>  <br></br>
                    <div
                      className="bg-[#30E3CA] h-2.5 rounded-full ">
                    </div> <br></br>
                    <h2 className="text-left ">Python-Intermediate</h2>  <br></br>
                    <div
                      className="bg-[#30E3CA] h-2.5 rounded-full ">
                    </div> <br></br>
                  </div>



                  <div className="text-center  shadow-lg p-10 rounded-xl my-10 dark:bg-white">
                    <h3 className="text-2xl font-medium pt-8 pb-2 text-teal-600">FrontEnd</h3>

                    <p className="py-2 text-teal-600">
                      FrontEnd skills performed on various projects, check projects.
                    </p>
                    <h2 className="text-left "> React.JS-Intermediate</h2><br></br>
                    <div
                      className="bg-[#30E3CA] h-2.5 rounded-full ">
                    </div><br></br>

                    <h2 className="text-left "> Next.JS-Basic</h2> <br></br>
                    <div
                      className="bg-[#30E3CA] h-2.5 rounded-full ">
                    </div><br></br>
                    <h2 className="text-left ">TailwindCSS-Intermediate</h2><br></br>
                    <div
                      className="bg-[#30E3CA] h-2.5 rounded-full ">
                    </div><br></br>
                    <h2 className="text-left ">Angular14-Basic</h2> <br></br>
                    <div
                      className="bg-[#30E3CA] h-2.5 rounded-full ">
                    </div><br></br>
                    <h2 className="text-left ">HTML/CSS-Experienced</h2>  <br></br>
                    <div
                      className="bg-[#30E3CA] h-2.5 rounded-full ">
                    </div> <br></br>
                    <h2 className="text-left ">JS-Intermediate</h2>  <br></br>
                    <div
                      className="bg-[#30E3CA] h-2.5 rounded-full ">
                    </div> <br></br>
                  </div>

                  <div className="text-center  shadow-lg p-10 rounded-xl my-10 dark:bg-white">
                    <h3 className="text-2xl font-medium pt-8 pb-2 text-teal-600">Data Analysis</h3>
                    <p className="py-2 text-teal-600">
                      DataAnalysis performed on python related projects.
                    </p>
                    <h2 className="text-left "> matplotlib-Intermediate</h2><br></br>
                    <div
                      className="bg-[#30E3CA] h-2.5 rounded-full ">
                    </div><br></br>

                    <h2 className="text-left "> Pandas-Basic</h2> <br></br>
                    <div
                      className="bg-[#30E3CA] h-2.5 rounded-full ">
                    </div><br></br>
                  </div>

                </div>
              </div>
            </div>

          </section>








          <section>
            <div className="lg:center ">

              <div className="text-center  shadow-lg p-10 rounded-xl my-10  dark:bg-black relative  bg-slate-50 ">
                <h3 className=" text-3xl py-1 mt-20 text-center font-burtons  dark:text-white">Contact Me</h3>
                <h2 className="text-2xl py-1 text-teal-600">Currently looking for full-time FrontEnd Developer opportunities, contact me if you have available position, thanks!</h2>
                <h2 className="text-xl text-gray-800 text-right dark:text-white">Email address</h2>
                <h2 className="text-xl text-gray-800 text-right dark:text-white">mk0805511@gmail.com</h2>
                <button
                  onClick={handleButtonEmail}
                  className="text-xl dark:bg-black text-gray-800 bg-slate-50 hover:bg-black hover:text-white border-solid border-2 font-Poppins py-2 px-4"
                >
                  Send email
                </button>
              </div>

            </div>
          </section>




        </main>
      </>
    </div>
  )
}








